### ISSUE TITLE
must specify a dash-separated username and module name.

### ISSUE THREAD

**Issue by belfast77** [dmccuk/puppet_legacy_manifest#1]
Hey DM.

First time trying, get the following error.

[root@sat6 puppetmanifestgenerator]# cat *.dm
epops /opt/vmware/epops-agent/conf/agent-properties
epops-agent epops-agent
[root@sat6 puppetmanifestgenerator]# ./manifest_creator.sh
Error: Could not generate directory "sat6.example.com-fstab", you must specify a dash-separated username and module name.
Error: Try 'puppet help module generate' for usage
./manifest_creator.sh: line 35: /opt/sat6.example.com/modules/build/fstab/manifests/init.pp: No such file or directory
./manifest_creator.sh: line 36: /opt/sat6.example.com/modules/build/fstab/manifests/init.pp: No such file or directory
sed: can't read /opt/sat6.example.com/modules/build/fstab/manifests/init.pp: No such file or directory
sed: can't read /opt/sat6.example.com/modules/build/fstab/manifests/init.pp: No such file or directory
sed: can't read /opt/sat6.example.com/modules/build/fstab/manifests/init.pp: No such file or directory
./manifest_creator.sh: line 40: /opt/sat6.example.com/modules/build/fstab/manifests/init.pp: No such file or directory
./manifest_creator.sh: line 69: /tmp/puppet_manifest_generator/files_managed_by_templates.dm: No such file or directory
./manifest_creator.sh: line 89: /tmp/puppet_manifest_generator/files_managed_by_file_line.dm: No such file or directory
./manifest_creator.sh: line 114: /tmp/puppet_manifest_generator/services_packages.dm: No such file or directory
Error: Could not generate directory "sat6.example.com-users", you must specify a dash-separated username and module name.
Error: Try 'puppet help module generate' for usage
./manifest_creator.sh: line 162: /tmp/puppet_manifest_generator/users_managed_by_puppet.dm: No such file or directory
sed: can't read /manifests/init.pp: No such file or directory
sed: can't read /manifests/init.pp: No such file or directory
./manifest_creator.sh: line 174: /manifests/init.pp: No such file or directory
[root@sat6 puppetmanifestgenerator]#

**Comment by dmccuk** [comment]
Hi Belfast77,

I've amended  the code if you want to clone it again. I've updated how I capture the host name. The puppet module generate command has a strict module naming convention. Hopefully this will resolve your issue.

Regards

**Comment by belfast77** [comment]
Hi DM,

Thanks for the quick response.
Slight issue, as the git clone creates /tmp/puppetmanifestgenerator however FILE_HOME is elswhere.

FILE_HOME=/tmp/puppet_manifest_generator

[root@sat6 tmp]# rm -rf puppetmanifestgenerator
[root@sat6 tmp]# git clone https://github.com/dmccuk/puppetmanifestgenerator.git
Cloning into 'puppetmanifestgenerator'...
remote: Counting objects: 170, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 170 (delta 17), reused 0 (delta 0), pack-reused 123
Receiving objects: 100% (170/170), 62.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (77/77), done.
[root@sat6 tmp]# cd puppetmanifestgenerator
[root@sat6 puppetmanifestgenerator]# ls 
files_managed_by_file_line.dm  files_managed_by_templates.dm  manifest_creator.sh  README.md  services_packages.dm  users_managed_by_puppet.dm
[root@sat6 puppetmanifestgenerator]# vi files_managed_by_templates.dm 
[root@sat6 puppetmanifestgenerator]# > files_managed_by_file_line.dm
[root@sat6 puppetmanifestgenerator]# vi services_packages.dm 
[root@sat6 puppetmanifestgenerator]# > users_managed_by_puppet.dm
[root@sat6 puppetmanifestgenerator]# ./manifest_creator.sh
./manifest_creator.sh: line 69: /tmp/puppet_manifest_generator/files_managed_by_templates.dm: No such file or directory
./manifest_creator.sh: line 89: /tmp/puppet_manifest_generator/files_managed_by_file_line.dm: No such file or directory
./manifest_creator.sh: line 114: /tmp/puppet_manifest_generator/services_packages.dm: No such file or directory
./manifest_creator.sh: line 162: /tmp/puppet_manifest_generator/users_managed_by_puppet.dm: No such file or directory
sed: can't read /manifests/init.pp: No such file or directory
sed: can't read /manifests/init.pp: No such file or directory
./manifest_creator.sh: line 174: /manifests/init.pp: No such file or directory
[root@sat6 puppetmanifestgenerator]# cat *.dm
epops /opt/vmware/epops-agent/conf/agent-properties
epops-agent epops-agent

epops-agent epops-agent

Cheers

**Comment by dmccuk** [comment]
I updated the project name and didn't update FILE_HOME. It's updated now. Go for another clone.

**Comment by belfast77** [comment]
Great, works a treat !!!
